### PR TITLE
Updating node service event timestamps

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by the2hill** [comment]
I can't see which checks have failed. What did I miss?

**Comment by cyrichardson** [comment]
Details button on right...

**Comment by cyrichardson** [comment]
This 128 error is a bug.... just add a blank line or other small change to your PR and it should build then.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-af0addae0b/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-af0addae0b/docs/cloud-load-balancers/v2/)

**Comment by cyrichardson** [comment]
@the2hill I made a minor change to force build. All is well with the build now.

**Comment by the2hill** [comment]
Thank you. I don't have permissions to see the details which is why i initially asked

**Comment by cyrichardson** [comment]
LGTM, @the2hill.

**Comment by cyrichardson** [comment]
@the2hill Let me know if you would like for me to merge this PR.

**Comment by the2hill** [comment]
I think we need to wait until we push out our Java8 upgrades first

**Comment by the2hill** [comment]
This one fell off radar. I think it's safe to merge this now.

**Comment by the2hill** [comment]
@cyrichardson ^

**Comment by cyrichardson** [comment]
@the2hill Merged now!

**Comment by the2hill** [comment]
@cyrichardson Could we go ahead and merge this one?

**Comment by the2hill** [comment]
Oh... srry, my thing wasn't updated :/

**Comment by cyrichardson** [comment]
Looking, @the2hill. Stay tuned.

**Comment by cyrichardson** [comment]
@the2hill It appears to be updated on the developer.rackspace.com site at 
https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/nodes/#list-node-service-events

Please let me know if you still don't see the update.

**Pull request merged**
