### PR TITLE
Accurately reflect proper rate limits

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 71 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-37b3f846b/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
I believe we can merge this one when ready. The other release one should be going out tomorrow. I'll have a few other doc updates coming this week too!

**Comment by cyrichardson** [comment]
Sounds good, @the2hill. 
Merging this one only for now.

**Comment by the2hill** [comment]
Thank you!

**Pull request merged**
