### PR TITLE
Fixes #152 - add body parameters descriptions

### LINKED ISSUE #152: inaccurate documentation to add node to load balancer
### Report an issue with the documentation

Document with the issue: https://github.com/rackerlabs/docs-cloud-load-balancers/blob/master/api-docs/cloud-load-balancers-v1/api-reference/methods/post-add-node-v1.0-account-loadbalancers-loadbalancerid-nodes.rst

**Report incorrect information:**
This document states that to add a node to a load balancer, 

> this operation does not accept a request body.

**This is incorrect; the operation *requires* a request body** and the very next section in the docs have an example request body.

### PR DESCRIPTION
**Pull request by cyrichardson**
and removes bogus paragraph about no request body required

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-87300acf71/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-87300acf71/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-87300acf71/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by cyrichardson** [comment]
@joeashcraft  Please review the changes at https://staging.developer.rackspace.com/build-87300acf71/docs/cloud-load-balancers/v1/api-reference/nodes/#add-node 
and let me know if you have further changes or if you agree that they can be merged as is. 
Thank  you!

**Comment by joeashcraft** [comment]
@cyrichardson the table of "the body parameters for the nodes object" looks good, except that it's **missing the second optional parameter "weight"**. Weight can be specified (or changed on existing nodes) even when the LB is not using a weighed algorithm (WEIGHTED_LEAST_CONNECTIONS or WEIGHTED_ROUND_ROBIN). While a LB is not using a weighted algorithm a nodes weight is stored and ignored. However, if the LB is changed to a weighted algorithm, the weight is used.

This is consistent with this paragraph in our docs, though my explanation above is a bit more elaborate. Furthermore, this paragraph in our docs does not mention the other weighted algorithm, WEIGHTED_LEAST_CONNECTIONS.

> If the WEIGHTED_ROUND_ROBIN load balancer algorithm mode is selected, then the caller should assign the relevant weights to the node as part of the weight attribute of the node element. When the algorithm of the load balancer is changed to WEIGHTED_ROUND_ROBIN and the nodes do not already have an assigned weight, the service automatically sets the weight to 1 for all nodes.

**Comment by joeashcraft** [comment]
The optional parameters for "add-node", as well as "update-node", are already well defined in the [header](https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/nodes/) section in **Table. Required and optional attributes**. We might link to or copy that table instead of recreating it here.

However, that table may be mislabeled as is lists only the optional attributes.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-48caa6c56a/docs/cloud-load-balancers/v1/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-48caa6c56a/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-48caa6c56a/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by cyrichardson** [comment]
@joeashcraft Thanks for your review comments. I updated the Nodes overview section, the POST node, and PUT node operations based on your review. Please review the changes and provide any additional feedback. I've summarized what I did below:

In the Nodes overview section, I added some info about the WEIGHTED_LEAST_CONNECTIONS algorithm as well as a link to the Algorithms section for more information. I did a little reorganization of the information in the section as well as renamed the attributes table to be "Optional attributes".

In the POST node operation description, I added the weight body parameter description, including info from your description of it. I think it's OK to have this body parameters table here with some info and a link back to the Nodes overview for more info. (Actually all of the operations should include such a table. When CLB v2 goes out later this month, I'll work on bringing the CLB v1 docs into consistency with our current docs style guide - I inherited CLB API docs from one of the writers who was laid off in March and haven't had a chance to go through the CLB v2 API docs to update to our current style guide yet.)

In the PUT node operation description, I removed the bogus paragraph about not requiring a body and added the body parameters table with links back to the Nodes overview.

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-d414db89ab/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-d414db89ab/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-d414db89ab/docs/cloud-load-balancers/v1/)

**Comment by joeashcraft** [comment]
Looking good!

update-node requires at least one of the optional node attributes (condition, weight, type).
Could you add 'type' as an optional attribute in the update-node table which has no name? The table appears immediately after this:

> The following table shows the body parameters for the node object for the request.  
At least one of the attributes is required.

**Comment by cyrichardson** [comment]
@joeashcraft Thanks for your quick review! After I add type to the body parms table, would you be OK with my merging and publishing the changes?

**Comment by joeashcraft** [comment]
@cyrichardson yes, everything else looks great.

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-c632d99d75/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-c632d99d75/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-c632d99d75/docs/cloud-load-balancers/v1/)

**Comment by cyrichardson** [comment]
Thanks, again, @joeashcraft , for your help with the docs! The changes are now published:
https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/nodes/

**Pull request merged**
