### PR TITLE
Update deconst file to v1.0 and add 2017 to conf.py

### PR DESCRIPTION
**Pull request by cyrichardson**
Internal v1.0 docs only.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-742b8a6ca8/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-742b8a6ca8/docs/cloud-load-balancers/v1/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-742b8a6ca8/docs/cloud-load-balancers/v1/)

**Comment by cyrichardson** [comment]
@nimbinatus When you have time, please merge this PR. It doesn't fix things in terms of the staging link to internal - it now points to v1.0 external rather than 2.0 external. But it does correct the version in deconst and adds 2017 to copyright. Thanks!

**Comment by cyrichardson** [comment]
Fixes #183

**Comment by the2hill** [comment]
:+1:

**Comment by cyrichardson** [comment]
@nimbinatus @the2hill Thanks!

**Comment by cyrichardson** [comment]
@nimbinatus I tried following the instructions in https://github.com/rackerlabs/docs-cloud-load-balancers/blob/master/internal-api-docs/cloud-load-balancers-v1/README.md  - the old way to update github enterprise. At Step 3 I got the following:

cath6184@MS90JHG8WL ~/documents/internal-load-balancers (master)
$ git pull --rebase upstream master
ERROR: Repository not found.
fatal: Could not read from remote repository.

When you have time, please check that I have the access that I need. 

Here is how my remotes are set up:

cath6184@MS90JHG8WL ~/documents/internal-load-balancers (master)
$ git remote -v
origin	git@github.rackspace.com:IX/internal-docs-cloud-feeds.git (fetch)
origin	git@github.rackspace.com:IX/internal-docs-cloud-feeds.git (push)
upstream	git@github.com:rackerlabs/docs-cloud-load-balancers-1.git (fetch)
upstream	git@github.com:rackerlabs/docs-cloud-load-balancers-1.git (push)

**Comment by nimbinatus** [comment]
@cyrichardson, why is the origin remote set to the one for cloud feeds?

I'll ping you directly.

**Comment by cyrichardson** [comment]
Awwgh! I think I see that and another problem... Ignore me for a bit @nimbinatus!

**Comment by cyrichardson** [comment]
Looks like I need work with https://github.rackspace.com/IX/internal-docs-cloud-load-balancers-1 - I don't see a repo without the -1.

**Comment by nimbinatus** [comment]
@cyrichardson, correct. Don't ask me why because I honestly have no idea :grinning:

**Pull request merged**
