### PR TITLE
Removed responses put update certificate mapping

### PR DESCRIPTION
**Pull request by dereknoblej**

### CODE REVIEW

**Comment by the2hill** [comment]
Are the build previews getting stuck?

**Comment by cyrichardson** [comment]
Let me check, @the2hill.

**Comment by cyrichardson** [comment]
@the2hill @dereknoblej 

There's a build error that I don't understand. I'm going to push a small changes to see if it occurs again.

Configuration found in api-docs/cloud-load-balancers-v1/_deconst.json: {
  "contentIDBase": "https://github.com/rackerlabs/docs-cloud-load-balancers/v1/",
  "githubUrl": "https://github.com/rackerlabs/docs-cloud-load-balancers/",
  "githubBranch": "master",
  "meta": {
    "preferGithubIssues": true
  }
}
Scripts not permitted to use method net.sf.json.JSON isEmpty

**Comment by the2hill** [comment]
Oh, interesting! Sound good. 

I suppose this one is pretty straight forward and LGTM. I seen the other one also seemed stuck also. Not a problem with either of these that I seen though, but going forward wanted to make sure we were still doing previews. Thank you

**Comment by cyrichardson** [comment]
@dereknoblej @the2hill My small change resulted in same build error message. The folks I talk to about this are not available. I hope someone can advise next steps tomorrow. I'm sorry!

**Comment by the2hill** [comment]
@cyrichardson The code looks good and I think we're about caught up with pub doc tickets. Not sure how the pipeline is, but if this is just a preview issue we can probably move forward. At least from dev review side. I think what we have left is on mgmt side anyways, will also have more mgmt once we implement some of the ops feature requests too!

**Comment by cyrichardson** [comment]
@the2hill Thanks for the info! OK. I will check in with the folks that know more about this tomorrow and see if we can merge without the preview.

**Comment by cyrichardson** [comment]
@the2hill And management side is a different build process that hasn't been changed recently, so hopefully less trouble-free for builds.

**Comment by cyrichardson** [comment]
@the2hill @dereknoblej I'm going to merge this one, even though no preview builds, and I will check to make sure production build works and changes are correct in externally-published docs (before I do this to the other PR).

**Comment by cyrichardson** [comment]
@the2hill @dereknoblej  Seems to have published to external web page just fine; https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/certificatemappings/#update-certificate-mapping

**Pull request merged**
