### PR TITLE
Updated API documentation to reflect that the default cipher profile …

### PR DESCRIPTION
**Pull request by dereknoblej**
…is the most inclusive, not the most secure

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 138 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f2ae763c4/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 139 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ca574f1e8/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
If john signed off on this, then it lgtm

**Comment by dereknoblej** [comment]
I showed it to John he did approve.

**Comment by cyrichardson** [comment]
OK, I'll merge @dereknoblej @the2hill

**Pull request merged**
