### PR TITLE
Updating release notes for 1.26.15

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 42 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-53d808cc8/docs/cloud-load-balancers/v2/). valid for 14 days

**Comment by the2hill** [comment]
I seem to be able to access these updates, and the v1 version seems to look accurate. The preview link above takes me to the v2 though: https://developer-revs.staging.deconst.org/build-53d808cc8/docs/cloud-load-balancers/v2/

**Comment by edwardjrp** [comment]
@the2hill Yes, the preview link will be that of the latest version of the document, when the preview link is built it will choose the latest in the list of available path for a document

**Comment by the2hill** [comment]
@edwardjrp gotcha, before we had both links, it's not a big deal I suppose but may confuse others as v2 is a completely separate thing that isn't released to the public

**Comment by edwardjrp** [comment]
@the2hill tricky to get as there is no way to know whats the version you are working on, teams have decided to have versioning with branches for this reason

**Comment by cyrichardson** [comment]
@the2hill Should we consider removing the v2 docs that were never published from the repo?

**Comment by the2hill** [comment]
@cyrichardson I suppose removing them is probably best bet at this point. If/when we do a v2 docs will likely be completely reworked

**Comment by cyrichardson** [comment]
@the2hill Would you please open an issue in this repo to have the v2 docs removed? Thank you!

**Comment by the2hill** [comment]
https://github.com/rackerlabs/docs-cloud-load-balancers/issues/224

**Comment by cyrichardson** [comment]
@the2hill I wondered if you were going to merge this one today.

**Comment by the2hill** [comment]
@cyrichardson We wanted to, but it looks like identity pushed out change that broke tests.. we *should* get things released today

**Comment by cyrichardson** [comment]
Just yell if I can help in any way, @the2hill.

**Comment by the2hill** [comment]
@cyrichardson I think we're ready to merge these two PR's

**Pull request merged**
