### PR TITLE
Add text about 503 response to fix issue 189

### LINKED ISSUE #189: Needs an explanation of what happens when connections are throttled
### Report an issue with the documentation

Describe your documentation issue in  the relevant section. Submit product operation or 
performance issues to the Rackspace product team at https://feedback.rackspace.com/.

**Link to documentation with issue:**  
https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/throttle-connections/

**Report missing information:**
Per https://one.rackspace.com/x/1Y5oGg , the Cloud Load Balancer will return a 503 Server Too Busy if it is throttling connections. However, we don't have that anywhere in the docs, and customers assume there's something wrong with the CLB when they see a 503 error.

If we could get the information in the one wiki article into the CLB docs, that would help clear things up for customers.

### PR DESCRIPTION
**Pull request by cyrichardson**
Fix #189

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-efa4734347/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-efa4734347/docs/cloud-load-balancers/v1/)

**Comment by cyrichardson** [comment]
@inflatador Please review the change for issue 189 and provider your feedback. Thanks!
https://staging.developer.rackspace.com/build-efa4734347/docs/cloud-load-balancers/v1/api-reference/throttle-connections/

**Comment by inflatador** [comment]
Hello @Catherine Richardson<mailto:catherine.richardson@RACKSPACE.COM> ,

Thanks for getting back.

I have a small phrasing change, to make clear that throttling is something the customer sets themselves.

Old (in “Throttle connections” section)

“Use the throttle connections operations to manage throttle configuration.
A common issue that you might encounter is that the load balancer exceeds the connection limit. After the connection limit is exceeded, the load balancer returns a 503 Server TooBusy response. You'll see something similar to the following example:
“
--
New (in “Create or update connection throttling configuration” section), beneath the text
“The connection throttling feature imposes limits on the number of connections per IP address to help mitigate malicious or abusive traffic to your applications. The attributes in the table that follows can be configured based on the traffic patterns for your sites.“

When connection throttling is active, and the connection limit is exceeded, the load balancer returns a 503 Server TooBusy response. You'll see something similar to the following example: (example text)
Let me know if you need more info.

~B

**Comment by cyrichardson** [comment]
Thanks, Brian. I’ll make the change shortly.

-Catherine

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-39665e1cf9/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-39665e1cf9/docs/cloud-load-balancers/v2/)

**Comment by cyrichardson** [comment]
@inflatador I will be on PTO tomorrow and Monday. I'm going to merge this PR but if you have more changes for this update, please let me know in the associated issue and I'll create another PR. Thanks!

**Pull request merged**
