### PR TITLE
Release notes for 1.26.10

### PR DESCRIPTION
**Pull request by the2hill**
**Quality audit reminder**

Doc team: While logged in using your O365 account, complete the quality checklist at http://bit.ly/2hwvBKX. Use the checklist for significant doc changes or additions submitted by you or a non-doc staff contributor.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-82c48cea24/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-82c48cea24/docs/cloud-load-balancers/v1/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-9ad50dbab4/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-9ad50dbab4/docs/cloud-load-balancers/v1/)

**Comment by the2hill** [comment]
Looks like I missed the linkage to show up under tab, looking for where that's supposed to be

**Comment by cyrichardson** [comment]
@the2hill I'm looking, too!

**Comment by cyrichardson** [comment]
Add file name entry to this file - https://github.com/rackerlabs/docs-cloud-load-balancers/blob/master/api-docs/cloud-load-balancers-v1/release-notes/index.rst

**Comment by cyrichardson** [comment]
@the2hill ^^

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-f5b75a6944/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-f5b75a6944/docs/cloud-load-balancers/v2/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-a59b62a508/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-a59b62a508/docs/cloud-load-balancers/v1/)

**Comment by the2hill** [comment]
@cyrichardson Thank you! I think it'd be best to get this merged first thing Monday morning. I'll ping in then

**Comment by the2hill** [comment]
@cyrichardson Can we go ahead and push this through

**Comment by cyrichardson** [comment]
@the2hill Done!

**Comment by the2hill** [comment]
Thank you!

**Comment by cyrichardson** [comment]
https://developer.rackspace.com/docs/cloud-load-balancers/v1/release-notes/#v1-26-10-april-1st-2019

**Pull request merged**
