### PR TITLE
Updating release notes, content caching and load balancer updates

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by the2hill** [comment]
I may have additional updates as I have a few more tickets to complete in this release. Just getting this staged for the time being.

**Comment by rackernexus** [comment]
Build 64 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-8c1dfef61/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
Can we go ahead and merge these @cyrichardson ?

**Comment by rackernexus** [comment]
Build 79 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f9754069f/docs/cloud-load-balancers/v1/). valid for 14 days

**Pull request merged**
