### PR TITLE
Adding ciphers management resource

### PR DESCRIPTION
**Pull request by the2hill**
**Quality audit reminder**

Doc team: While logged in using your O365 account, complete the quality checklist at http://bit.ly/2hwvBKX. Use the checklist for significant doc changes or additions submitted by you or a non-doc staff contributor.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-54256edefa/docs/cloud-load-balancers/v2/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-54256edefa/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-54256edefa/docs/cloud-load-balancers/v1/)

**Comment by the2hill** [comment]
@cyrichardson @nimbinatus It's possible I broke it, but the internal link seems to take me to 'v2'. Is there a fix for this, or maybe the endpoint to view manually?
I have an update to make, will push soon.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-25517d3794/docs/cloud-load-balancers/v1/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-25517d3794/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-25517d3794/docs/cloud-load-balancers/v2/)

**Comment by cyrichardson** [comment]
@the2hill V2 to was in process when the Public Cloud things changed and then V2 was stopped. Let me figure out how to point only to v1 for internal. Will that work for you?

**Comment by cyrichardson** [comment]
@the2hill So you didn't break it!! Just something lying around from when major changes happened.

**Comment by the2hill** [comment]
That'll work for me. Just want to verify the internal changes. Glad it wasn't me this go! :) Thank you

**Comment by cyrichardson** [comment]
@the2hill I opened an issue that Laura and I will work on a little later - https://github.com/rackerlabs/docs-cloud-load-balancers/issues/181 

For now, you can access the v1.0 internal docs from the internal landing page at https://pages.github.rackspace.com/IX/internal-docs-landing-page/ - the internal docs have a last updated date of 4/11/2016. 

There it opens https://pages.github.rackspace.com/IX/internal-docs-cloud-load-balancers-1/latest/ - although there is a  v2.0 in the top left navigation area, the right side correctly notes this is the v1.0 internal docs.

**Comment by the2hill** [comment]
Perfect! Thank you for the updates and information!

**Comment by the2hill** [comment]
We need to define profiles, document the 'default'/temp solution in public. Also, document POST mgmt ciphers resource. https://review.gerrithub.io/#/c/367918/10/api/mgmt-web/src/main/java/org/openstack/atlas/api/mgmt/resources/CiphersResource.java

**Comment by cyrichardson** [comment]
Understood!

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-14dd67a3b2/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-14dd67a3b2/docs/cloud-load-balancers/v1/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-14dd67a3b2/docs/cloud-load-balancers/v1/)

**Comment by the2hill** [comment]
wait, how is there a conflict ><

**Comment by cyrichardson** [comment]
Humm... no idea! Internal-api-docs has been deleted from this repo and is now GitHub Enterprise.

**Comment by the2hill** [comment]
Oh, then this code should be elsewhere?

**Comment by the2hill** [comment]
I added the code to index here, are mgmt updates supposed to go to another repo? I'm sorry, I'm a bit confused.

**Comment by cyrichardson** [comment]
So sorry.  Yes internal docs are now in github.rackspace.com/IX.  Can you please more PRs for internal docs there in the cloud load balances repo?

**Comment by the2hill** [comment]
Will do, I'll have to figure how to move them.

**Comment by cyrichardson** [comment]
Thank you! Happy to help if I can.

**Comment by cyrichardson** [comment]
https://github.rackspace.com/IX/internal-docs-cloud-load-balancers-1 is the repo and you should have access.

If you'd like I can recreate your PR there (not sure how to move them either). Let me know if you'd like for me to do that. Thanks, @the2hill. So for the switcheroo troubles!

**Comment by the2hill** [comment]
Closing and opening in: https://github.rackspace.com/IX/internal-docs-cloud-load-balancers-1/pull/4

**Pull request closed without merging**
