### PR TITLE
CLB-913 Need to Update documentation for disable tls1.1 feature

### PR DESCRIPTION
**Pull request by MadhaviLReddy**
Updated the docs for disabling TLS1.1 feature.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-1e8ec83375/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-1e8ec83375/docs/cloud-load-balancers/v1/)

**Comment by the2hill** [comment]
This lgtm too. I'll have release notes noting this update soon along with a code release within~2weeks. We should merge near the time we release. If we can't get release pushed out before our sprint is ended I will circle back and we can probably go ahead and merge it because release shouldn't happen too far after

**Comment by cyrichardson** [comment]
@the2hill Just checking in to see if you are close to being ready to merge this one and the others associated with your release. Thanks!

**Comment by edwardjrp** [comment]
build me

**Pull request merged**
