### PR TITLE
Add HTTP/2 information

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 181 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b7e994f96/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 183 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a45ee36c0/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 185 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4dd65e7ab/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by dereknoblej** [comment]
LGTM

**Pull request merged**
