### PR TITLE
Updating release notes for 1.26.30

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by the2hill** [comment]
This will go out tomorrow after release during release quorum

**Comment by rackernexus** [comment]
Build 134 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-eded111d5/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
Let me know when you want me to merge!

**Comment by rackernexus** [comment]
Build 135 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-24dd1a6e3/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
I think we're good to go ahead and release these!

**Comment by the2hill** [comment]
not sure it pinged with the edit, reping: @cyrichardson

**Comment by rackernexus** [comment]
Build 136 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ec8ad1dd8/docs/cloud-load-balancers/v1/). valid for 14 days

**Pull request merged**
