### PR TITLE
Updating for upcoming 1.26.11 release notes

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by the2hill** [comment]
This will get merged around the same time the other is; near/during/right after release.

**Comment by cyrichardson** [comment]
@the2hill Please check out my editorial changes and see if you disagree with any of them. Thanks!

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-a7641d5cb6/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-a7641d5cb6/docs/cloud-load-balancers/v2/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-594a589f98/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-594a589f98/docs/cloud-load-balancers/v1/)

**Comment by the2hill** [comment]
Had to update release :/

**Comment by cyrichardson** [comment]
@the2hill Please let me know if you need any assistance merging this for publishing.

**Comment by the2hill** [comment]
@cyrichardson I can't see why it's failing, but yes, this is something that needs to go out today with the release. Along with the other PR we were holding on.

**Comment by cyrichardson** [comment]
@the2hill Our publishing process changed last Friday. I'll have to pass this PR and the other one over to our tools team and see if they can  help get them both published today. I'll keep you informed.

**Comment by the2hill** [comment]
@cyrichardson Thank you, I was unaware. Is there something we can do to make this process easy in the future? Or anything we need to do now?

**Comment by cyrichardson** [comment]
@the2hill Nothing for now... I've contacted those working on the publishing changes and let them know the 2 PRs need to publish today...

**Comment by catlook** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Pull request merged**
