### PR TITLE
CLB-376 - IPv6 Share IP Call not working

### PR DESCRIPTION
**Pull request by NamrataAnand**
-Updating add shared virtual IP version 6 request in JSON and XML format
    -Adding few validation point to be considered for add shared virtual IP version 6 API

### CODE REVIEW

**Comment by the2hill** [comment]
This looks good but.. this proves that there was some revert issues that happened. This is kinda frustrating.

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-d51f84d0aa/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-d51f84d0aa/docs/cloud-load-balancers/v2/)

**Comment by cyrichardson** [comment]
@NamrataAnand Thanks for your docs contribution! I fixed the note syntax and modified the text a little. Please let me know if you ware ready and would like for me to merge this PR>

**Comment by NamrataAnand** [comment]
@cyrichardson changes looks fine to me. I have verified it on https://staging.developer.rackspace.com/build-d51f84d0aa/docs/cloud-load-balancers/v1/ 
I cannot find the changes on 
https://staging.developer.rackspace.com/build-d51f84d0aa/docs/cloud-load-balancers/v2/

**Comment by cyrichardson** [comment]
@namrataAnand You’ll need to make the same changes in the files in the v2 doc directory. (The files are not shared.)

**Comment by cyrichardson** [comment]
@NamrataAnand Note that v2 of the Load Balancers API was never published to https://developer.rackspace.com/docs/. Work on that release was stopped when organizational changes took place. 

Please let me know if you would like for me to merge this PR.

**Comment by NamrataAnand** [comment]
@cyrichardson yes you can merge the change to v1.

**Comment by cyrichardson** [comment]
@NamrataAnand Done! Thanks a ton for your docs contribution!

**Pull request merged**
