### PR TITLE
LBS v1.0 refactoring updates to match template

### PR DESCRIPTION
**Pull request by meker12**
- Updated conf.py to match template and correct pep8 errors
- Updated heading separators
- Wrapped body content to 79 characters
- API reference changes - shortened refills
- Release notes changes - updated to match template
- Updated general api info topics with edited copy in template

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-5940e1b16d/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-5940e1b16d/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-5940e1b16d/docs/cloud-load-balancers/v1/)

**Comment by meker12** [comment]
@cyrichardson Can you QE the v1 refactored content using the [checklist](https://github.com/rackerlabs/docs-cloud-load-balancers/issues/161)?  Let me know if you run into problems, or if you see anything missing from the checklist.

**Comment by cyrichardson** [comment]
@meker12 Sure thing. Starting now.

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-3237764af8/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-3237764af8/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-3237764af8/docs/cloud-load-balancers/v1/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-4eefc552a7/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-4eefc552a7/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-4eefc552a7/docs/cloud-load-balancers/v1/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-9783e172c7/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-9783e172c7/docs/cloud-load-balancers/v1/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-9783e172c7/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-9783e172c7/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-44604ad3f4/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-44604ad3f4/docs/cloud-load-balancers/v1/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-44604ad3f4/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-30145a16b8/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-30145a16b8/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-30145a16b8/docs/cloud-load-balancers/v1/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-85ec5b4bc9/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-85ec5b4bc9/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-85ec5b4bc9/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-85ec5b4bc9/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-85ec5b4bc9/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-d5a3349bd1/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-d5a3349bd1/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-d5a3349bd1/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-95bfb9ec7f/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-95bfb9ec7f/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-95bfb9ec7f/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-95bfb9ec7f/docs/cloud-load-balancers/v1/). :bow:

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-9e3ce9fbf2/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-9e3ce9fbf2/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-9e3ce9fbf2/docs/cloud-load-balancers/v1/)

**Pull request merged**
