### PR TITLE
Clb563

### PR DESCRIPTION
**Pull request by dereknoblej**

### CODE REVIEW

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 108 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c9a9371ae/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
-1 seems the updated examples have broken formatting that's not rendering

**Comment by rackernexus** [comment]
Build 109 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f932efda3/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
@the2hill Please recheck to see if you approve formatting changes.

**Comment by rackernexus** [comment]
Build 110 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-cdf571f07/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 111 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-124b0f28b/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
This lgtm

**Pull request merged**
