### PR TITLE
Updated the shared Ip json/xml request and response Virtual ip's and …

### PR DESCRIPTION
**Pull request by dereknoblej**
…id's to match the lb that they are paired with

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 98 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-763a32483/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
Need to ensure XML matches JSON. Also, should update the "Example Create load balancer with IPv4/IPv6: JSON request" to use similar ID's to reference the shared IP's. That example is just showing you can use both, but still part of the shared example. Maybe that title should read


Example Create load balancer with IShared Pv4/IPv6: JSON request

**Comment by rackernexus** [comment]
Build 99 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1dfdfa414/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
Looks like one of the xml id's were missed, still showing '13' where json has '15'. 

And the Example Create load balancer: XML response

shouldn't have the namespace tag, Don't think you added that, but we should make it consistent. While where on this page, it looks like theres some other examples in the LIST LB's that has the tag we should pull out. 

Example: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
Those tags are a given and they seem to break code highlighting. We should def remove them where we can.

**Comment by rackernexus** [comment]
Build 100 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-000b00c1b/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
+2 lgtm

This and the other PR from me are read for merge

**Pull request merged**
