### PR TITLE
Remove unpublished v2 docs

### PR DESCRIPTION
**Pull request by cyrichardson**
With the new publishing system using RSI, preview published to the lastest version which causes confusion if you are updating the v1 docs.

Note: v2 has never been published and was last updated several years ago.

### CODE REVIEW

**Comment by cyrichardson** [comment]
@the2hill Please review.
@edwardjrp Please note this new PR. I'm not sure if you need to do some manual tasks related to it or not.

**Comment by cyrichardson** [comment]
Fixes issues #225.

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 44 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1d4cb6c89/docs/cloud-load-balancers/v2/). valid for 14 days

**Comment by cyrichardson** [comment]
@the2hill If you approve, I will merge. :-)

**Comment by the2hill** [comment]
Preview is broken for me here but commit looks accurate. +1

**Pull request merged**
