### PR TITLE
Updating release notes for 1.26.29

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 129 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1cb10b0d3/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
Those lgtm. This is ready to merge when you are I believe. Thank you!

**Comment by rackernexus** [comment]
Build 130 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-63e763efa/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
Merging now!

**Comment by the2hill** [comment]
Thank you!

**Pull request merged**
