### PR TITLE
Refactor LB v1 API docs

### PR DESCRIPTION
**Pull request by meker12**
**Quality audit reminder**

Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-005fc0b406/docs/cloud-load-balancers/v1/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-005fc0b406/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-005fc0b406/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-57ce772d88/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-57ce772d88/docs/cloud-load-balancers/v1/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-57ce772d88/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-0f3413efa5/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-0f3413efa5/docs/cloud-load-balancers/v1/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-0f3413efa5/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-2b02ef804c/docs/cloud-load-balancers/v2/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-2b02ef804c/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-2b02ef804c/docs/cloud-load-balancers/v1/developer-guide/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-c317a41b5e/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-c317a41b5e/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-c317a41b5e/docs/cloud-load-balancers/v1/developer-guide/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-cf39c015b7/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-cf39c015b7/docs/cloud-load-balancers/v1/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-cf39c015b7/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-6c850beaac/docs/cloud-load-balancers/v1/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-6c850beaac/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-6c850beaac/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by meker12** [comment]
@kmsholcomb  Can you review the latest PR for the v1 refactoring.  If it looks OK, then I'll merge.

**Comment by kmsholcomb** [comment]
Just one nit, and a question, @meker12:

- In the "Concepts" topic, the heading for "Active Health Monitor" is not at the right level. It looks like it is supposed to be a subheading under "Health Monitor."

- I thought we decided to put all the release notes into one long topic? Did we change our minds on that? It works as is, too, but I was just wondering...

Otherwise, it all looks great!

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-2cb6601bd0/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-2cb6601bd0/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-2cb6601bd0/docs/cloud-load-balancers/v1/developer-guide/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-a8b9bff847/docs/cloud-load-balancers/v1/developer-guide/)
* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-a8b9bff847/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-a8b9bff847/docs/cloud-load-balancers/v2/developer-guide/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-36b56724f1/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-36b56724f1/docs/cloud-load-balancers/v2/developer-guide/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-36b56724f1/docs/cloud-load-balancers/v1/developer-guide/)

**Pull request merged**
