### PR TITLE
removed spacing from addCertificateMapping

### PR DESCRIPTION
**Pull request by dereknoblej**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
build me

**Comment by cyrichardson** [comment]
Checking with others on build issue, @dereknoblej.

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 153 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4ee36e451/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
@dereknoblej Is this the correction you are going for? https://developer-revs.staging.deconst.org/build-4ee36e451/docs/cloud-load-balancers/v1/api-reference/certificatemappings/#add-certificate-mapping

**Comment by dereknoblej** [comment]
Yes, this is the correction I am looking for.

**Comment by cyrichardson** [comment]
https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/certificatemappings/#add-certificate-mapping 
@dereknoblej publishing to the developer site is successful.

**Pull request merged**
