### PR TITLE
Fix issue 192 by adding notes about apikey vs apiKey

### LINKED ISSUE #192: Loadbalancer SSL documentation
When updating an SSL certificate on SSL Termination the private key field is named "privatekey" whereas when updating an SSL on Certificate Mapping it is instead "privateKey" ( note the capital K on key ). The API seems to be case sensitive and report a 400 error. Is it either possible to update the API to make is not case sensitive or update the documentation to make this clear?

Thanks

Adam

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #192

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-75b1caaf4d/docs/cloud-load-balancers/v2/)
* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-75b1caaf4d/docs/cloud-load-balancers/v1/)

**Comment by cyrichardson** [comment]
@phantomadam. Please review this PR to see if this fixes the issue you ran into.

**Comment by phantomadam** [comment]
Yeah that’s perfect, thanks :)

**Comment by cyrichardson** [comment]
Thanks for your review! Merged, @phantomadam.

**Pull request merged**
