### PR TITLE
Updating cipher profile docs for CLB-920

### PR DESCRIPTION
**Pull request by the2hill**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by the2hill** [comment]
Pending further discussion. Do not merge

**Comment by cyrichardson** [comment]
I'm just going to push a minor change so the build will complete.

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-load-balancers-v1`](https://staging.developer.rackspace.com/build-d7d7a0f478/docs/cloud-load-balancers/v1/)
* [`api-docs/cloud-load-balancers-v2`](https://staging.developer.rackspace.com/build-d7d7a0f478/docs/cloud-load-balancers/v2/)

**Comment by the2hill** [comment]
@cyrichardson Looks like we're a go for this. Policy updated in all regions, can we go ahead and push this out?

**Comment by cyrichardson** [comment]
@the2hill Sure! I'll merge now.

**Comment by the2hill** [comment]
Thank you

**Pull request merged**
