### PR TITLE
added two new default ciphers

### PR DESCRIPTION
**Pull request by dereknoblej**
Added TLS_AES_256_GCM_SHA384 and TLS_AES_128_GCM_SHA256 to list of default ciphers

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 162 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a85010351/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 163 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e03914ae4/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 164 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-fad815d47/docs/cloud-load-balancers/v1/). valid for 14 days

**Comment by the2hill** [comment]
This should be good, just need ops go ahead I suppose

**Comment by rackernexus** [comment]
Build 165 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1902442d4/docs/cloud-load-balancers/v1/). valid for 14 days

**Pull request merged**
